<?php
namespace LiveTest\Config\Tags\TestSuite;


require_once __DIR__.'/../../../../../../src/LiveTest/Config/Tags/TestSuite/Base.php';

/**
 * Test class for Base.
 * Generated by PHPUnit on 2011-05-16 at 20:53:24.
 */
class BaseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Base
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
