<?php
namespace Unit\LiveTest\Config\Tags\TestSuite;


use LiveTest\Config\Parser\Parser;

use LiveTest\Config\TestSuite;

use Unit\LiveTest\Config\Tags\TestSuite\Mockups\ExtendsBase as Base;

/**
 * Test class for Base.
 * Generated by PHPUnit on 2011-05-16 at 20:53:24.
 */
class BaseTest extends \PHPUnit_Framework_TestCase
{
    
    /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testConstructFailingOnConfigParameters()
    {    
        $base = new Base('test',new TestSuite(), new Parser('Test'));
    }
    
	/**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testConstructFailingOnTestSuiteParameter()
    {    
        $base = new Base(array(),null, new Parser('Test'));
    }
    
	/**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testConstructFailingOnParserParameter()
    {    
        $base = new Base(array(), new TestSuite(), null);
    }  
    
    
    public function testProcess()
    {    
        $base = new Base(array(), new TestSuite(), new Parser('Test'));
        $base->process();
        
        $this->assertEquals("OK", $base->getConfig());
        $this->assertEquals("OK", $base->getParameters());
    }  
}
?>
