<?php
namespace LiveTest\Config\Request;


require_once '/Users/mikelohmann/Sites/livetest.local/LiveTest_mikelohmann/src/LiveTest/Config/Request/LiveTest.php';

/**
 * Test class for LiveTest.
 * Generated by PHPUnit on 2011-05-16 at 20:49:51.
 */
class LiveTestTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LiveTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LiveTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testCreateRequestsFromParameters().
     */
    public function testCreateRequestsFromParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreatePageRequestFromParameters().
     */
    public function testCreatePageRequestFromParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetIdentifier().
     */
    public function testGetIdentifier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
