<?php
namespace Unit\LiveTest\TestRun;


use LiveTest\TestRun\Properties;

/**
 * Test class for Properties.
 * Generated by PHPUnit on 2011-05-17 at 07:47:04.
 */
class PropertiesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Properties
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $uri = $this->getMock("Uri");
//        $uri->expects($this->any())
//            ->method('concatUri')
//            ->will($this->returnValue('/index.html'));
//
//        var_dump($uri->concatUri());
//
//        //$this->object = new Properties();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetDefaultDomain().
     */
    public function testGetDefaultDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTestSets().
     */
    public function testGetTestSets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateByYamlFile().
     */
    public function testCreateByYamlFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
