<?php
namespace Unit\LiveTest\TestRun;

use LiveTest\Connection\Session\Session;

use LiveTest\Config\TestSuite;

use Base\Www\Uri;
use LiveTest\Connection\Request\Symfony;
use LiveTest\TestRun\Properties;

/**
 * Test class for Properties.
 * Generated by PHPUnit on 2011-05-17 at 07:47:04.
 */
class PropertiesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Properties
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      $uri = new Uri('http://www.example.com');  
      $testSuiteConfig = new TestSuite(new Session($uri));      
      $this->object = new Properties($testSuiteConfig, $uri);
    }

    public function testGetDefaultDomain()
    {
        $this->assertEquals("http://www.example.com/",  $this->object->getDefaultDomain()->toString());
    }

    public function testGetTestSets()
    {
        $this->assertEquals(array(), $this->object->getTestSets());
    }

    public function test__toString()
    {
      $this->assertEquals("",$this->object->__toString());
    }

    /**
     * @expectedException \LiveTest\ConfigurationException
     */
    public function testCreateByYamlFileConfigException()
    {
       Properties::createByYamlFile('none', new Uri("http://www.example.com"));
    }
    
	/**
     * @expectedException LiveTest\ConfigurationException
     */
    public function testCreateByYamlFileConfigurationException()
    {
       Properties::createByYamlFile(__DIR__.'/Fixtures/testsuite_error.yml', new Uri("http://www.example.com"));
    }
}
?>
