<?php
use LiveTest\TestRun\Run;
use LiveTest\TestRun\Properties;
use Base\Config\Yaml;

use Base\Www\Uri;
use Base\Config\Config;
use LiveTest\Extensions\Null;

include_once __DIR__.'/Mockups/HttpClientMockup.php';

/**
 * Test class for Run.
 * Generated by PHPUnit on 2011-02-08 at 08:05:37.
 */
class RunTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Run
     */
    protected $object;
    protected $uri;
    protected $configProperties;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      $this->config = new Yaml( __DIR__.'/Fixtures/config.yml', true);
      $this->uri = new Uri('http://www.example.com/index.html');
      
      $this->configProperties = new Properties($this->config, $this->uri);
      $this->object = new Run($this->configProperties);
    }
    
     /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testAddExtensionException()
    {
       $this->object->addExtension();
    }
    
    public function testAddExtension()
    {
       $this->object->addExtension(new Null(1));
       $extensions = $this->object->getExtensions();
       
       
    }
    
     /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testConstruct()
    {
       new Run(array());
       
       
    }
    
    public function testRunZendHttpClientAdapterException()
    {
      $this->object->addExtension(new Null(1));
      $this->object->setHttpClient(new HttpClientMockup());
       
    }
}
?>
